import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import NavigationBar from "@/components/NavigationBar";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const adminMenuItems = [
  {
    name: "Overview",
    pathName: "/",
    icons: "/Assets/dashboardIcon.svg",
    id: 1,
  },
  {
    name: "Customers",
    pathName: "/customer",
    icons: "/Assets/coursesIcon.svg",
    id: 2,
  },

];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className=" flex min-h-screen bg-[#F3F3F3]">
          <SideBar menuItems={adminMenuItems} />
          <div className="sm:ml-[12.6635rem] flex-grow md:p-6">
            <NavigationBar current="Overview" />
            <main className="mt-5 ">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
